apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: yoojin
spec:
  # type: ClusterIP 
  # 생략시 default는 ClusterIP.
  # NodePort, LoadBalancer등의 타입을 사용시 service를 통해 외부접근가능
  ports:
  - port: 80 # Service가 노출하는 포트
    targetPort: 80 # Pod의 컨테이너 포트
  selector:
    app: my-nginx # 라벨 셀렉터를 통해 매핑할 Pod 선택
  